<?php

namespace AppBundle\Repository;

/**
 * CourseStudentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourseStudentRepository extends \Doctrine\ORM\EntityRepository
{
}
