<?php

namespace AppBundle\Repository;

/**
 * deans_officeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class deans_officeRepository extends \Doctrine\ORM\EntityRepository
{
}
