<?php

namespace AppBundle\Repository;

/**
 * deans_office_syllabusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class deans_office_syllabusRepository extends \Doctrine\ORM\EntityRepository
{
}
