<?php

namespace AppBundle\Repository;

/**
 * DWMRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DWMRepository extends \Doctrine\ORM\EntityRepository
{
}
