<?php

namespace AppBundle\Repository;

/**
 * external_coordinatorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class external_coordinatorRepository extends \Doctrine\ORM\EntityRepository
{
}
