<?php

namespace AppBundle\Repository;

/**
 * internal_coordinatorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class internal_coordinatorRepository extends \Doctrine\ORM\EntityRepository
{
}
