<?php

namespace AppBundle\Repository;

/**
 * StudentEnrolledCourseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentEnrolledCourseRepository extends \Doctrine\ORM\EntityRepository
{
}
