<?php

namespace AppBundle\Repository;

/**
 * UniversitiesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UniversitiesRepository extends \Doctrine\ORM\EntityRepository
{
}
